import FWCore.ParameterSet.Config as cms

muToTau = cms.EDAnalyzer("TagProbeFitTreeProducer",
	tagProbePairs = cms.InputTag("tnpAnyMuAnyTau"),
	arbitration   = cms.string("OneProbe"),
	#massForArbitration = cms.double(91),
	variables = cms.PSet(
		px = cms.string("px"),
		py = cms.string("py"),
		pz = cms.string("pz"),
		pt = cms.string("pt"),
		En = cms.string("energy"),
		charge = cms.string("charge"),
		#pxTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.px : -1"),
		#pyTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.py : -1"),
		#pzTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.pz : -1"),
		#ptTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.pt : -1"),
		#pTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.p : -1"),
		#chargeTrackRef = cms.string("? leadPFChargedHadrCand.trackRef.isNonnull ? leadPFChargedHadrCand.trackRef.charge : -9"),
		#pxGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.px : -1"),
		#pyGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.py : -1"),
		#pzGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.pz : -1"),
		#ptGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.pt : -1"),
		#pGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.p : -1"),
		#chargeGsfTrackRef = cms.string("? leadPFChargedHadrCand.gsfTrackRef.isNonnull ? leadPFChargedHadrCand.gsfTrackRef.charge : -9"),
		ptJet = cms.string("pfJetRef.pt"),
		eta = cms.string("eta"),
		abseta = cms.string("abs(eta)"),
		phi = cms.string("phi"),
		DecayModeRaw = cms.string("decayMode"),
		DecayModeOld = cms.string("tauID('decayModeFindingOldDMs')"),
		DecayMode = cms.string("tauID('decayModeFinding')"),
		HpsLooseCombIsoDBCorr = cms.string("tauID('byLooseCombinedIsolationDeltaBetaCorr')"),
		HpsMediumCombIsoDBCorr = cms.string("tauID('byMediumCombinedIsolationDeltaBetaCorr')"),
		HpsTightCombIsoDBCorr = cms.string("tauID('byTightCombinedIsolationDeltaBetaCorr')"),
		HpsLooseCombIsoDBCorr3Hits = cms.string("tauID('byLooseCombinedIsolationDeltaBetaCorr3Hits')"),
		HpsMediumCombIsoDBCorr3Hits = cms.string("tauID('byMediumCombinedIsolationDeltaBetaCorr3Hits')"),
		HpsTightCombIsoDBCorr3Hits = cms.string("tauID('byTightCombinedIsolationDeltaBetaCorr3Hits')"),
		HpsAntiMuLoose = cms.string("tauID('againstMuonLoose')"),
		HpsAntiMuMedium = cms.string("tauID('againstMuonMedium')"),
		HpsAntiMuTight = cms.string("tauID('againstMuonTight')"),
		HpsAntiMuLoose2 = cms.string("tauID('againstMuonLoose2')"),
		HpsAntiMuMedium2 = cms.string("tauID('againstMuonMedium2')"),
		HpsAntiMuTight2 = cms.string("tauID('againstMuonTight2')"),
		HpsAntiMuLoose3 = cms.string("tauID('againstMuonLoose3')"),
		HpsAntiMuTight3 = cms.string("tauID('againstMuonTight3')"),
		HpsAntiMuLooseMVA = cms.string("tauID('againstMuonLooseMVA')"),
		HpsAntiMuMediumMVA = cms.string("tauID('againstMuonMediumMVA')"),
		HpsAntiMuTightMVA = cms.string("tauID('againstMuonTightMVA')"),
		HpsAntiMuMVARaw = cms.string("tauID('againstMuonMVAraw')"),

	),
	flags = cms.PSet(
		passingIsoLooseMuonVetoLoose =  cms.InputTag("passingIsoLooseMuonVetoLoose"),
		passingIsoLooseMuonVetoMedium =  cms.InputTag("passingIsoLooseMuonVetoMedium"),
		passingIsoLooseMuonVetoTight =  cms.InputTag("passingIsoLooseMuonVetoTight"),
		passingIsoLooseMuonVetoLoose2 =  cms.InputTag("passingIsoLooseMuonVetoLoose2"),
		passingIsoLooseMuonVetoMedium2 =  cms.InputTag("passingIsoLooseMuonVetoMedium2"),
		passingIsoLooseMuonVetoTight2 =  cms.InputTag("passingIsoLooseMuonVetoTight2"),
		passingIsoLooseMuonVetoLoose3 =  cms.InputTag("passingIsoLooseMuonVetoLoose3"),
		passingIsoLooseMuonVetoTight3 =  cms.InputTag("passingIsoLooseMuonVetoTight3"),
		passingIsoLooseMuonVetoLooseMVA =  cms.InputTag("passingIsoLooseMuonVetoLooseMVA"),
		passingIsoLooseMuonVetoMediumMVA =  cms.InputTag("passingIsoLooseMuonVetoMediumMVA"),
		passingIsoLooseMuonVetoTightMVA =  cms.InputTag("passingIsoLooseMuonVetoTightMVA"),
	),
	tagVariables = cms.PSet(
		px = cms.string("px"),
		py = cms.string("py"),
		pz = cms.string("pz"),
		pt = cms.string("pt"),
		ptErr = cms.string("innerTrack.ptError"),
		En = cms.string("energy"),
		charge = cms.string("charge"),
		eta = cms.string("eta"),
		abseta = cms.string("abs(eta)"),
		phi = cms.string("phi"),
		Mt =  cms.InputTag("addUserVariables","Mt"),
    		puMCWeightRun2012 =  cms.InputTag("addUserVariables","puMCWeightRun2012"),
		triggerBitSingleMu = cms.InputTag("addUserVariables","triggerBitSingleMu"),
		muTriggerMatching = cms.InputTag("addUserVariables","muTriggerMatching"),
		muMVAMet = cms.InputTag("addUserVariables","mvaMET"),
		muPFIsolation = cms.InputTag("addUserVariables","PFRelIsoDB04v2"),
	),
	tagFlags = cms.PSet(
   		IsoMu24_eta2p1   = cms.string("!triggerObjectMatchesByPath('HLT_IsoMu24_eta2p1_v*',1,0).empty()"),
	),
	pairVariables = cms.PSet(
		dr = cms.string("deltaR(daughter('muon').eta,daughter('muon').phi,daughter('tau').eta,daughter('tau').phi)"),
		charge = cms.string("charge")
	),
	pairFlags = cms.PSet(
	),
	isMC = cms.bool( True ),
	tagMatches = cms.InputTag("tagMcMatch") ,
	probeMatches  = cms.InputTag("probeMcMatch"),
	motherPdgId = cms.vint32(23),
	makeMCUnbiasTree = cms.bool(True),
	checkMotherInUnbiasEff = cms.bool(True),
	allProbes = cms.InputTag("probeAnyTau"),
	addRunLumiInfo = cms.bool(True),
	addEventVariablesInfo = cms.bool(True)
	)
